server:
  port: 8761

spring:
  cloud:
    config:
      enabled: false    ##是否加入配置服务

eureka:
  client:
    register-with-eureka: false #是否注册到eurika
    registry-fetch-interval-seconds: 30 #定期的更新客户端的服务清单 30秒更新一次
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://user:123456@127.0.0.1:8761/eureka/


#eurika界面的账号密码
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456


---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
