server:
  port: 8999  ##端口修改 前端工程也需要改造

spring:
  application:
    name: svr-yihu-admin-server
  data:
    elasticsearch:
      cluster-name: jkzl #es集群的名字
      cluster-nodes: 172.19.103.68:9300  #多个逗号分割
      cluster-nodes-jest: http://172.19.103.68:9200  #多个逗号分割
      repositories:
        enabled: true
      properties:
        client:
          transport:
            sniff: true  #开启嗅探集群  用nginx代理一层过后会出现ip解析失败问题
      jest:
        discovery-enabled: true #开启嗅探
        conn-timeout: 60 # 连接时间单位是秒
        read-timeout: 60 # 读取时间单位是秒
        multith-readed: true #开启多线程
        max-total-connection: 50 ##最大连接
        max-connection-idle-time: 50 #最大等待时间


#logging:
#  file: ${logging.path}demo-eureka.log
#  path: G:\idea_workspace\jkzl_git\jkzl-start\logs\
#  level:
#    root: INFO

---
spring:
  profiles: jwdev
  data:
    elasticsearch:
      cluster-name: jkzl #es集群的名字
      cluster-nodes: 172.19.103.68:9300  #多个逗号分割
      cluster-nodes-jest: http://172.19.103.68:9200  #多个逗号分割


---
spring:
  profiles: jwtest
  data:
    elasticsearch:
      cluster-name: jkzl #es集群的名字
      cluster-nodes: 172.19.103.68:9300  #多个逗号分割
      cluster-nodes-jest: http://172.19.103.68:9200  #多个逗号分割

---
spring:
  profiles: jwprod
  data:
    elasticsearch:
      cluster-name: jkzl #es集群的名字
      cluster-nodes: 172.19.103.68:9300  #多个逗号分割
      cluster-nodes-jest: http://172.19.103.68:9200  #多个逗号分割