server:
  port: 10020

##如果有配置服务的话，远程服务器和本地服务器配置不一致的情况下，优先远程的为主  git上 svr-base ->  git application ->本地 appliction ->本地 bootstarp
spring:
  application:
    name:  svr-quota  ##注册到发现服务的id 如果id一样 eurika会自动做负载

  http:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB



---
spring:
  profiles: dev

---
spring:
  profiles: test


---
spring:
  profiles: prod

