server:
  port: 10020

spring:
  application:
    name:  svr-user  ##注册到发现服务的id 如果id一样 eurika会自动做负载

  cloud:
    config:
      enabled: false    ##是否加入配置服务


eureka:
  client:
    serviceUrl:
      #http://账号:密码@127.0.0.1:8761/eureka/
      defaultZone: http://user:123456@127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true #启动监控检查
  instance:
    #eurika使用IP不使用host
    prefer-ip-address: true
    #定制化在eurika中显示的名称
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}




---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
