spring:
  jmx:
    enabled: false

server:
  port: 1221

security:
  user:
    name: jw
    password: jkzl

eureka:
  client:
    healthcheck:
      enabled: true #启动监控检查
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka
  instance:
    #eurika使用IP不使用host
    prefer-ip-address: true
    #定制化在eureka中显示的名称
    ##instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}


