spring:
  jmx:
    enabled: false

server:
  port: 1221

security:
  user:
    name: jw
    password: jkzl

eureka:
  client:
    healthcheck:
      enabled: true #启动监控检查
    serviceUrl:
      defaultZone: http://jw:jkzl@172.19.103.33:8761/eureka
  instance:
    #eurika使用IP不使用host
    prefer-ip-address: true


