server:
  port: 1221



---
spring:
  profiles: jwdev
#
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: 172.17.110.201
#          defaultBrokerPort: 9092
#          zkNodes: 172.17.110.201
#          defaultZkPort: 2181
#          replicationFactor: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka


---
spring:
  profiles: jwtest

eureka:
  client:
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka

---
spring:
  profiles: jwprod


eureka:
  client:
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka
