server:
  port: 1221

management:
  port: ${server.port}

info:
  app:
    name: ConfigurationService
    description: 全局配置服务
    version: 1.0.0




---
spring:
  profiles: dev

eureka:
  instance:
    ip-address: http://${discovery.name}:${discovery.password}@127.0.0.1:8761
    prefer-ip-address: true

---
spring:
  profiles: test

eureka:
  instance:
    ip-address: http://${discovery.name}:${discovery.password}@172.19.103.73:8761
    prefer-ip-address: true

---
spring:
  profiles: prod

eureka:
  instance:
    ip-address: http://${discovery.name}:${discovery.password}@11.1.2.21:8761
    prefer-ip-address: true