

##配置服务的账号密码
security:
  user:
    name: jw
    password:  jkzl


---
spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka


---
spring:
  profiles: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka

---
spring:
  profiles: prod


eureka:
  client:
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka
