server:
  port: 1221

##配置服务的账号密码
security:
  user:
    name: jw
    password:  jkzl


---
spring:
  profiles: jwdev

eureka:
  client:
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka


---
spring:
  profiles: jwtest

eureka:
  client:
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka

---
spring:
  profiles: jwprod


eureka:
  client:
    serviceUrl:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka
