server:
  port: 10001

zuul:
  ignored-services: '*'
  sensitive-headers:
  routes:
    svr-iot:
      path: /iot/**
      serviceId: svr-iot
    svr-base:
      path: /base/**
      serviceId: svr-base-sxy
    demo:
      path: /baidu/**
      url: https://www.baidu.com

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0