server:
  port: 10001

zuul:
  ignored-services: '*'
  sensitive-headers:
  routes:
    svr-iot:
      path: /iot/**
      serviceId: svr-iot
    svr-base:
      path: /base/**
      serviceId: svr-base
    demo:
      path: /baidu/**
      url: https://www.baidu.com