##如果有配置服务的话，远程服务器和本地服务器配置不一致的情况下，优先远程的为主
server:
  port: 10020

spring:
  application:
    name:  svr-base  ##注册到发现服务的id 如果id一样 eurika会自动做负载

---
spring:
  profiles: dev

---
spring:
  profiles: test


---
spring:
  profiles: prod
