##如果有配置服务的话，远程服务器和本地服务器配置不一致的情况下，优先远程的为主  git上 svr-base ->  git application ->本地 appliction ->本地 bootstarp
server:
  port: 10020

spring:
  application:
    name:  svr-base  ##注册到发现服务的id 如果id一样 eurika会自动做负载

eureka:
  client:
    healthcheck:
      enabled: true #启动监控检查
  instance:
    #eurika使用IP不使用host
    prefer-ip-address: true
    #定制化在eurika中显示的名称
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}



---
spring:
  profiles: dev

---
spring:
  profiles: test


---
spring:
  profiles: prod

