##如果有配置服务的话，远程服务器和本地服务器配置不一致的情况下，优先远程的为主  git上 svr-base ->  git application ->本地 appliction ->本地 bootstarp
spring:
  application:
    name:  svr-base-lith  #注册到发现服务的id 如果id一样 eurika会自动做负载


#hibernate 配置
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: false
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy





---
spring:
  profiles: jwdev

---
spring:
  profiles: jwtest


---
spring:
  profiles: jwprod

