##如果有配置服务的话，远程服务器和本地服务器配置不一致的情况下，优先远程的为主  git上 svr-base ->  git application ->本地 appliction ->本地 bootstarp
spring:
  application:
    name: svr-base  #注册到发现服务的id 如果id一样 eurika会自动做负载
#  jmx:
#    default-domain: svr-base
  jmx:
    enabled: true

#  data:
#    elasticsearch:
#      cluster-name: jkzl #es集群的名字
#      cluster-nodes: 172.19.103.68:9300  #多个逗号分割
#      cluster-nodes-jest: http://172.19.103.68:9200  #多个逗号分割
#      repositories:
#        enabled: true
#      properties:
#        client:
#          transport:
#            sniff: false #开启嗅探集群  用nginx代理一层过后会出现ip解析失败问题



management:
  security:
    enabled: false #关闭 refresh的权限认证

health:
  config:
    enabled: true

endpoints:
  info:
    enabled: true



---
spring:
  profiles: jwdev

jw:
  sms:
    url: 123
    code: 123
    name: 123
    password: 123

---
spring:
  profiles: jwtest


---
spring:
  profiles: jwprod

