cache: # 1-内存 2-redis
  type: 1
  expire-time: 2 #单位为小时
  refresh-time: 1.5

spring:
  redis:
    host: 172.19.103.88 # ip
    port: 6379 # R端口
    database: 0 # 默认使用DB0
    timeout: 0 # 连接超时时间（毫秒）
      #sentinel:
      #  master: # Name of Redis server.
      #  nodes: # Comma-separated list of host:port pairs.
    pool: ##连接池配置
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 1 # 连接池中的最小空闲连接

