spring:
  application:
    name: svr-discovery
  jmx:
    enabled: false

server:
  port: 8761
  display-name: svr-discovery

#eureka界面的账号密码
security:
  basic:
    enabled: true
  user:
    name: jw
    password: jkzl

eureka:
  server:
    enable-self-preservation: false  #是否开启自我保护模式，默认为true。
    eviction-interval-timer-in-ms: 60000 #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 30 #定期的更新客户端的服务清单 30秒更新一次
    fetch-registry: false #如果是做高可用的发现服务那就要改成true
    service-url:
      defaultZone: http://jw:jkzl@127.0.0.1:8761/eureka